version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      drawshift-db:
        condition: service_healthy
      drawshift-redis:
        condition: service_healthy

  drawshift-db:
    image: postgres:latest
    env_file: .env-db
    ports:
      - '5432:5432'
    volumes:
      - dev-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -h drawshift-db
      interval: 30s
      timeout: 60s
      retries: 5

  drawshift-redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 10s
      retries: 5
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  dev-volume:
