# Generated by Django 5.0.6 on 2024-06-25 17:45

import django.utils.timezone
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, storage=storages.backends.s3.S3Storage(bucket_name='original-data'), upload_to=''),
            preserve_default=False,
        ),
    ]
