# Generated by Django 5.0.6 on 2024-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_drawing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='image',
        ),
        migrations.AddField(
            model_name='drawing',
            name='base64_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
