# Generated by Django 3.2 on 2021-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
