# Generated by Django 3.2 on 2021-09-18 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_drawing_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='svg_file',
        ),
        migrations.AddField(
            model_name='drawing',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=[], size=None),
        ),
    ]
