# Generated by Django 3.2 on 2021-06-17 07:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210616_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default=users.models.generate_unique_string, max_length=256, unique=True),
        ),
    ]
